### ISSUE TITLE
Code Review 16 December 2021

### ISSUE THREAD

**Issue by ShadyShawkat** [vechicin/Leaderboard#3]
# Hi @vechicin 👋🏻,

Awesome work on the project. The code is really clean and organized. 💯 🚀 
# Here are some suggestions :
 - You can use `Required` here. That will cause a visual error message to appear (You can show an alert too).
 https://github.com/vechicin/Leaderboard/blob/254a2ec1e0c47781e4b860e90530562aa04aac83/src/index.html#L21-L22

That will also get rid of the usage of this line of code.
https://github.com/vechicin/Leaderboard/blob/254a2ec1e0c47781e4b860e90530562aa04aac83/src/index.js#L34

### Again, good job working on the project. the code is very professionally written. 👍🏻 😃

**Comment by vechicin** [comment]
# Hi @ShadyShawkat, thanks a lot for your comments!
While I did consider your suggestion, I ended up creating a custom message to let the user know they need to have both input fields correctly filled out! The end result is very similar to your suggestion so I definitely took it into account.

## Once again, thanks for your suggestion!
